openapi: 3.0.2
x-stoplight:
  id: dgk6z19rq7mpx
info:
  title: shriken_openapi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /clubs:
    get:
      summary: get club list
      tags:
        - club
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  clubs:
                    type: array
                    items:
                      $ref: '#/components/schemas/Club'
              examples:
                my-example:
                  value:
                    clubs:
                      - clubColor: red
                        icon: /upload/club/1296/1325eed031d6c6a627abd1ff3ec5c295_180_180.jpeg
                        id: 1296
                        name: Seira FC Living room
                        plans:
                          - id: 1481
                            image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/1296/UZK6XDFI.jpeg'
                            info: FC限定の内容を一緒に楽しみましょう♪
                            name: スタンダードプラン
                          - id: 1482
                            image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/1296/UZK6XDFI.jpeg'
                            info: FC限定の内容を一緒に楽しみましょう♪
                            name: プレミアムプラン
                        slug: seira-livingroom
                        unReadCount: 1
                      - clubColor: red
                        icon: /img/sample/logo/default.png
                        id: 1
                        name: FANCLOVEのファンクラブ
                        plans:
                          - id: 1784
                            image: null
                            info: 鍵アカサロンを試しに使ってみるためのプランです。入会メリットなどは特にありません。
                            name: 鍵アカサロン仮利用のためのプラン
                        slug: fanclove
                        unReadCount: 0
                      - clubColor: aqua
                        icon: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/icon/RNBTTOOFI25GTVWJ61KWTMCVTW3CSY.jpeg'
                        id: 4077
                        name: 心音ふぁんくラブ
                        plans:
                          - id: 5261
                            image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/4077/N44FI231.jpeg'
                            info: "SNSでは見られない、写真、動画などの投稿が毎日見られる。佐々木心音をより身近に感じられて、応援できるプラン。\r\n\r\n\r\n「最近、SNS疲れをしていませんか？ほっこりするものだけ観たい、と思ったりする時が、癒される方が居てくださるのなら嬉しいな。　by 心音」"
                            name: 心音☺︎ぷらん
                        slug: kokone
                        unReadCount: 2
                      - clubColor: red
                        icon: /upload/club/2826/5dc2b130aef8622cc122b64243134963_180_180.jpeg
                        id: 2826
                        name: マジシャンけんとのfanclub
                        plans:
                          - id: 3594
                            image: null
                            info: "レパートリー400を超えラスベガスで修行した私が無料で解説出来ないマジックを解説致します✨\r\n更にこの動画だけでは解らない！となっても大丈夫です。月に１回、時間をとりマンツーマンでレクチャー致します！"
                            name: マジシャンけんとのfanclub
                          - id: 3619
                            image: null
                            info: "レパートリー400を超えラスベガスで修行した私が無料で解説出来ないマジックを解説致します✨\r\n更にこの動画だけでは解らない！となっても大丈夫です。今後無制限マジックレクチャーをマンツーマンで行います！"
                            name: AD PREMIUM
                        slug: magic-kento
                        unReadCount: 0
      operationId: get-clubs
      description: 入会しているクラブ一覧を取得する
      parameters: []
  '/clubs/{id}/channels':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get club's channels
      tags:
        - club
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  channels:
                    type: array
                    items:
                      $ref: '#/components/schemas/Channel'
              examples:
                my-example:
                  value:
                    channels:
                      - IsOwner: true
                        createdAt: '2022-06-07T14:59:43+09:00'
                        description: test用のチャンネルです
                        id: 51
                        isJoinAsUser: true
                        name: test
                        plans:
                          - id: 1481
                            image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/1296/UZK6XDFI.jpeg'
                            info: FC限定の内容を一緒に楽しみましょう♪
                            name: スタンダードプラン
                        updatedAt: '2022-06-07T14:59:43+09:00'
                        unReadCount: 0
                      - IsOwner: true
                        createdAt: '2022-06-07T14:59:57+09:00'
                        description: test2用のチャンネルです
                        id: 52
                        isJoinAsUser: true
                        name: test2
                        plans:
                          - id: 1481
                            image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/1296/UZK6XDFI.jpeg'
                            info: FC限定の内容を一緒に楽しみましょう♪
                            name: スタンダードプラン
                        updatedAt: '2022-06-07T14:59:57+09:00'
                        unReadCount: 1
      operationId: get-clubs-id
      description: クラブに紐付いているチャネル一覧を取得する
  /channels:
    post:
      summary: create channel
      operationId: post-channels
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  channel:
                    $ref: '#/components/schemas/Channel'
              examples:
                my-example:
                  value:
                    channel:
                      id: 105
                      name: test!
                      description: test用のチャンネルです
                      isOwner: false
                      isJoinAsUser: true
                      plans:
                        - id: 1481
                          image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/1296/UZK6XDFI.jpeg'
                          info: FC限定の内容を一緒に楽しみましょう♪
                          name: スタンダードプラン
                      createdAt: '2022-06-07T14:59:43+09:00'
                      updatedAt: '2022-06-07T14:59:43+09:00'
                      unReadCount: 0
      description: チャネルの作成
      tags:
        - channel
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                planIds:
                  type: array
                  items:
                    type: number
              required:
                - name
                - description
                - planIds
        description: ''
  '/channels/{id}/name':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    patch:
      summary: update channel name
      operationId: patch-channels-id-name
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  channel:
                    $ref: '#/components/schemas/Channel'
              examples:
                my-example:
                  value:
                    channel:
                      IsOwner: true
                      createdAt: '2022-06-07T14:59:43+09:00'
                      description: test用のチャンネルです
                      id: 51
                      isJoinAsUser: true
                      name: 更新されたtest
                      plans:
                        - id: 1481
                          image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/1296/UZK6XDFI.jpeg'
                          info: FC限定の内容を一緒に楽しみましょう♪
                          name: スタンダードプラン
                      updatedAt: '2022-06-07T19:59:43+09:00'
                      unReadCount: 0
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      tags:
        - channel
  '/channels/{id}/plans':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    patch:
      summary: update channel plans
      operationId: patch-channels-id-name
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  channel:
                    $ref: '#/components/schemas/Channel'
              examples:
                my-example:
                  value:
                    channel:
                      IsOwner: true
                      createdAt: '2022-06-07T14:59:43+09:00'
                      description: test用のチャンネルです
                      id: 51
                      isJoinAsUser: true
                      name: 更新されたtest
                      plans:
                        - id: 1481
                          image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/1296/UZK6XDFI.jpeg'
                          info: FC限定の内容を一緒に楽しみましょう♪
                          name: プレミアムプラン
                      updatedAt: '2022-06-07T19:59:43+09:00'
                      unReadCount: 0
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                planIds:
                  type: array
                  items:
                    type: number
              required:
                - planIds
      tags:
        - channel
  '/channels/{id}/typing':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: ''
      operationId: post-channels-id-typing
      responses:
        '200':
          description: OK
      description: |-
        「〇〇さんが入力中。。。」を知らせるデータを送る。
        Request Body と Response Bodyは無しの想定
      tags:
        - channel
  '/channels/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    delete:
      summary: delete channel
      operationId: delete-channels-id
      responses:
        '200':
          description: OK
      tags:
        - channel
  '/channels/{id}/channel_comments':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get channel comments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  channelComments:
                    type: array
                    items:
                      $ref: '#/components/schemas/ChannelComment'
                  nextCursor:
                    type: string
                    nullable: true
              examples:
                my-example:
                  value:
                    channelComments:
                      - id: 1
                        content: test!!!
                        attachedFiles:
                          - id: 0
                            fileType: string
                            url: string
                            isDeleted: true
                            deletedAt: string
                            createdAt: string
                        profile:
                          id: 1
                          name: test_user
                          thumbnail: 'https://picsum.photos/id/237/200/300'
                          isProfilePublic: true
                        isRead: true
                        isDeleted: false
                        deletedAt: '2019-08-24T14:15:22Z'
                        createdAt: '2019-08-24T14:15:22Z'
                        updatedAt: '2019-08-24T14:15:22Z'
                        reactions:
                          - reaction:
                              id: 1
                              name: smail
                              image: "\U0001F974"
                            counts: 2
                            profiles:
                              - id: 10
                                name: testUser
                                thumbnail: 'https://picsum.photos/536/354'
                                isProfilePublic: true
                              - id: 11
                                name: 山田さん
                                thumbnail: 'https://picsum.photos/536/354'
                                isProfilePublic: true
                        threadInfo:
                          profiles:
                            - id: 2
                              name: test_user2
                              thumbnail: 'https://picsum.photos/seed/picsum/200/300'
                              isProfilePublic: true
                            - id: 3
                              name: test_user3
                              thumbnail: 'https://picsum.photos/id/1005/200/300'
                              isProfilePublic: true
                          commentCount: 2
                          lastCommentDateTime: '2019-08-24T14:15:22Z'
                      - id: 2
                        content: test投稿です！
                        attachedFiles:
                          - id: 0
                            fileType: string
                            url: string
                            isDeleted: true
                            deletedAt: string
                            createdAt: string
                        profile:
                          id: 2
                          name: test_user2
                          thumbnail: 'https://picsum.photos/seed/picsum/200/300'
                          isProfilePublic: true
                        isRead: true
                        isDeleted: false
                        deletedAt: '2019-08-24T14:15:22Z'
                        createdAt: '2019-08-24T14:15:22Z'
                        updatedAt: '2019-08-24T14:15:22Z'
                        reactions:
                          - reaction:
                              id: 2
                              name: star-struck
                              image: "\U0001F929"
                            counts: 1
                            profiles:
                              - id: 10
                                name: testUser
                                thumbnail: string
                                isProfilePublic: true
                        threadInfo:
                          profiles:
                            - id: 1
                              name: test_user
                              thumbnail: 'https://picsum.photos/id/237/200/300'
                              isProfilePublic: true
                          commentCount: 1
                          lastCommentDateTime: '2019-08-24T14:15:22Z'
                      - id: 3
                        content: 新しい投稿テストです
                        attachedFiles:
                          - id: 0
                            fileType: string
                            url: string
                            isDeleted: true
                            deletedAt: string
                            createdAt: string
                        profile:
                          id: 2
                          name: test_user2
                          thumbnail: 'https://picsum.photos/seed/picsum/200/300'
                          isProfilePublic: true
                        isRead: true
                        isDeleted: false
                        deletedAt: '2019-08-24T14:15:22Z'
                        createdAt: '2019-08-24T14:15:22Z'
                        updatedAt: '2019-08-24T14:15:22Z'
                        reactions:
                          - reaction:
                              id: 3
                              name: expressionless face
                              image: "\U0001F611"
                            counts: 1
                            profiles:
                              - id: 10
                                name: testUser
                                thumbnail: string
                                isProfilePublic: true
                          - reaction:
                              id: 4
                              name: rat
                              image: "\U0001F439"
                            counts: 2
                            profiles:
                              - id: 14
                                name: 山本さん
                                thumbnail: 'https://picsum.photos/200/300/?blur'
                                isProfilePublic: true
                              - id: 15
                                name: 山岡さん
                                thumbnail: 'https://picsum.photos/id/870/200/300?grayscale&blur=2'
                                isProfilePublic: true
                          - reaction:
                              id: 5
                              name: waving hand
                              image: "\U0001F44B"
                            counts: 1
                            profiles:
                              - id: 15
                                name: 山岡さん
                                thumbnail: 'https://picsum.photos/id/870/200/300?grayscale&blur=2'
                                isProfilePublic: true
                        threadInfo:
                          profiles: []
                          commentCount: 0
                          lastCommentDateTime: ''
                      - id: 4
                        content: "初めまして、山岡です。よろしくお願いいたします\U0001F64F"
                        attachedFiles:
                          - id: 1
                            fileType: image/png
                            url: 'https://picsum.photos/200/300'
                            isDeleted: true
                            deletedAt: '2019-08-24T14:15:22Z'
                            createdAt: '2019-08-24T14:15:22Z'
                        profile:
                          id: 15
                          name: 山岡さん
                          thumbnail: 'https://picsum.photos/id/870/200/300?grayscale&blur=2'
                          isProfilePublic: true
                        isRead: true
                        isDeleted: false
                        deletedAt: '2019-08-24T14:15:22Z'
                        createdAt: '2019-08-24T14:15:22Z'
                        updatedAt: '2019-08-24T14:15:22Z'
                        reactions:
                          - reaction:
                              id: 1
                              name: smail
                              image: "\U0001F974"
                            counts: 2
                            profiles:
                              - id: 10
                                name: testUser
                                thumbnail: 'https://picsum.photos/536/354'
                                isProfilePublic: true
                              - id: 11
                                name: 山田さん
                                thumbnail: 'https://picsum.photos/536/354'
                                isProfilePublic: true
                        threadInfo:
                          profiles:
                            - id: 2
                              name: test_user2
                              thumbnail: 'https://picsum.photos/seed/picsum/200/300'
                              isProfilePublic: true
                            - id: 3
                              name: test_user3
                              thumbnail: 'https://picsum.photos/id/1005/200/300'
                              isProfilePublic: true
                          commentCount: 2
                          lastCommentDateTime: '2019-08-24T14:15:22Z'
                      - id: 5
                        content: "初めまして、山本と申します。よろしくお願いいたします\U0001F64F"
                        attachedFiles:
                          - id: 1
                            fileType: image/png
                            url: 'https://picsum.photos/200/300'
                            isDeleted: true
                            deletedAt: '2019-08-24T14:15:22Z'
                            createdAt: '2019-08-24T14:15:22Z'
                          - id: 2
                            fileType: image/png
                            url: 'https://picsum.photos/200/300'
                            isDeleted: true
                            deletedAt: '2019-08-24T14:15:22Z'
                            createdAt: '2019-08-24T14:15:22Z'
                          - id: 3
                            fileType: image/png
                            url: 'https://picsum.photos/200/300'
                            isDeleted: true
                            deletedAt: '2019-08-24T14:15:22Z'
                            createdAt: '2019-08-24T14:15:22Z'
                          - id: 4
                            fileType: image/png
                            url: 'https://picsum.photos/200/300'
                            isDeleted: true
                            deletedAt: '2019-08-24T14:15:22Z'
                            createdAt: '2019-08-24T14:15:22Z'
                        profile:
                          id: 14
                          name: 山本さん
                          thumbnail: 'https://picsum.photos/200/300/?blur'
                          isProfilePublic: true
                        isRead: true
                        isDeleted: false
                        deletedAt: '2019-08-24T14:15:22Z'
                        createdAt: '2019-08-24T14:15:22Z'
                        updatedAt: '2019-08-24T14:15:22Z'
                        threadInfo:
                          profiles:
                            - id: 2
                              name: test_user2
                              thumbnail: 'https://picsum.photos/seed/picsum/200/300'
                              isProfilePublic: true
                            - id: 3
                              name: test_user3
                              thumbnail: 'https://picsum.photos/id/1005/200/300'
                              isProfilePublic: true
                          commentCount: 2
                          lastCommentDateTime: '2019-08-24T14:15:22Z'
                    nextCursor: string
      operationId: get-channels-id-channel_comments
      tags:
        - channel_comment
      parameters:
        - schema:
            type: string
          in: query
          name: cursor
          description: ページネーション用
  /channel_comments:
    post:
      summary: create channel comment
      operationId: post-channel_comments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  channelComment:
                    $ref: '#/components/schemas/ChannelComment'
              examples:
                my-example:
                  value:
                    channelComment:
                      id: 4
                      content: てすとで投稿しています！
                      attachedFiles:
                        - id: 0
                          fileType: string
                          url: string
                          isDeleted: true
                          deletedAt: string
                          createdAt: string
                      profile:
                        id: 103
                        name: test_user103
                        thumbnail: 'https://picsum.photos/1002/1/200/300'
                        isProfilePublic: true
                      isRead: true
                      isDeleted: false
                      deletedAt: '2019-08-24T14:15:22Z'
                      createdAt: '2019-08-24T14:15:22Z'
                      updatedAt: '2019-08-24T14:15:22Z'
                      reactions:
                        - reaction:
                            id: 0
                            name: string
                            image: string
                          counts: 0
                          profiles:
                            - id: 0
                              name: string
                              thumbnail: string
                              isProfilePublic: true
                      threadInfo:
                        profiles: []
                        commentCount: 0
                        lastCommentDateTime: '2019-08-24T14:15:22Z'
      tags:
        - channel_comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                channelId:
                  type: integer
                threadStartCommentId:
                  type: integer
                  nullable: true
                content:
                  type: string
                files:
                  type: array
                  items:
                    type: object
                    properties:
                      url:
                        type: string
                      contentType:
                        type: string
                        description: text/plain
        description: ''
      description: 投稿するテキスト、ファイルを登録する。
  '/channel_comments/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    patch:
      summary: update channel comment
      operationId: patch-channel_comments-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  channelComment:
                    $ref: '#/components/schemas/ChannelComment'
              examples:
                my-example:
                  value:
                    channelComment:
                      id: 1
                      content: コメントが更新されました
                      attachedFiles:
                        - id: 0
                          fileType: string
                          url: string
                          isDeleted: true
                          deletedAt: string
                          createdAt: string
                      profile:
                        id: 1
                        name: test_user
                        thumbnail: 'https://picsum.photos/id/237/200/300'
                        isProfilePublic: true
                      isRead: true
                      isDeleted: false
                      deletedAt: '2019-08-24T14:15:22Z'
                      createdAt: '2019-08-24T14:15:22Z'
                      updatedAt: '2019-08-24T14:15:22Z'
                      reactions:
                        - reaction:
                            id: 1
                            name: smail
                            image: "\U0001F974"
                          counts: 2
                          profiles:
                            - id: 10
                              name: testUser
                              thumbnail: 'https://picsum.photos/536/354'
                              isProfilePublic: true
                            - id: 11
                              name: 山田さん
                              thumbnail: 'https://picsum.photos/536/354'
                              isProfilePublic: true
                      threadInfo:
                        profiles:
                          - id: 2
                            name: test_user2
                            thumbnail: 'https://picsum.photos/seed/picsum/200/300'
                            isProfilePublic: true
                          - id: 3
                            name: test_user3
                            thumbnail: 'https://picsum.photos/id/1005/200/300'
                            isProfilePublic: true
                        commentCount: 2
                        lastCommentDateTime: '2019-08-24T14:15:22Z'
      tags:
        - channel_comment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
        description: ''
    delete:
      summary: delete channel comment
      operationId: delete-channel_comments-id
      responses:
        '200':
          description: OK
      tags:
        - channel_comment
  '/channel_comments/{id}/thread_comments':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: get thread comments
      tags:
        - channel_comment
      responses:
        '200':
          description: nextCursorでページネーションすると、threadCommentsの要素が変わる。originalCommentは基本変わらない。
          content:
            application/json:
              schema:
                type: object
                properties:
                  originalComment:
                    $ref: '#/components/schemas/ThreadComment'
                  threadComments:
                    type: array
                    items:
                      $ref: '#/components/schemas/ThreadComment'
                  nextCursor:
                    type: string
                    nullable: true
              examples:
                my-example:
                  value:
                    originalComment:
                      id: 1
                      content: test!!!
                      attachedFiles:
                        - id: 0
                          fileType: string
                          url: string
                          isDeleted: true
                          deletedAt: string
                          createdAt: string
                      profile:
                        id: 1
                        name: test_user
                        thumbnail: 'https://picsum.photos/id/237/200/300'
                        isProfilePublic: true
                      isRead: true
                      isDeleted: false
                      deletedAt: '2019-08-24T14:15:22Z'
                      createdAt: '2019-08-24T14:15:22Z'
                      updatedAt: '2019-08-24T14:15:22Z'
                      reactions:
                        - image: string
                          counts: 0
                          profiles:
                            - id: 0
                              name: string
                              thumbnail: string
                              isProfilePublic: true
                    threadComments:
                      - id: 201
                        content: スレッドのコメントです！
                        attachedFiles:
                          - id: 0
                            fileType: string
                            url: string
                            isDeleted: true
                            deletedAt: string
                            createdAt: string
                        profile:
                          id: 2
                          name: test_user2
                          thumbnail: 'https://picsum.photos/seed/picsum/200/300'
                          isProfilePublic: true
                        isRead: true
                        isDeleted: true
                        deletedAt: '2019-08-24T14:15:22Z'
                        createdAt: '2019-08-24T14:15:22Z'
                        updatedAt: '2019-08-24T14:15:22Z'
                        reactions:
                          - reaction:
                              id: 0
                              name: string
                              image: string
                            counts: 0
                            profiles:
                              - id: 0
                                name: string
                                thumbnail: string
                                isProfilePublic: true
                      - id: 202
                        content: 別の方からのスレッドコメント！！
                        attachedFiles:
                          - id: 0
                            fileType: string
                            url: string
                            isDeleted: true
                            deletedAt: string
                            createdAt: string
                        profile:
                          id: 3
                          name: test_user3
                          thumbnail: 'https://picsum.photos/id/1005/200/300'
                          isProfilePublic: true
                        isRead: true
                        isDeleted: true
                        deletedAt: '2019-08-24T14:15:22Z'
                        createdAt: '2019-08-24T14:15:22Z'
                        updatedAt: '2019-08-24T14:15:22Z'
                        reactions:
                          - reaction:
                              id: 0
                              name: string
                              image: string
                            counts: 0
                            profiles:
                              - id: 0
                                name: string
                                thumbnail: string
                                isProfilePublic: true
                    nextCursor: string
      operationId: get-channel_comments-id-thread-comments
      parameters:
        - schema:
            type: string
          in: query
          name: cursor
          description: ページネーション用
      description: スレッドのコメント一覧取得API
  '/channel_comments/{id}/read':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    patch:
      summary: update channel comment read
      operationId: patch-channel_comments-id-read
      responses:
        '200':
          description: 指定したチャンネルIDが属しているクラブとチャンネルのレスポンスを返します。
          content:
            application/json:
              schema:
                type: object
                properties:
                  club:
                    $ref: '#/components/schemas/Club'
                  channel:
                    $ref: '#/components/schemas/Channel'
              examples:
                my-example:
                  value:
                    club:
                      clubColor: red
                      icon: /upload/club/1296/1325eed031d6c6a627abd1ff3ec5c295_180_180.jpeg
                      id: 1296
                      name: Seira FC Living room
                      plans:
                        - id: 1481
                          image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/1296/UZK6XDFI.jpeg'
                          info: FC限定の内容を一緒に楽しみましょう♪
                          name: スタンダードプラン
                      slug: seira-livingroom
                      unReadCount: 0
                    channel:
                      IsOwner: true
                      createdAt: '2022-06-07T14:59:43+09:00'
                      description: test用のチャンネルです
                      id: 51
                      isJoinAsUser: true
                      name: test
                      plans:
                        - id: 1481
                          image: 'https://fanclove.s3.ap-northeast-1.amazonaws.com/club/plan-image/1296/UZK6XDFI.jpeg'
                          info: FC限定の内容を一緒に楽しみましょう♪
                          name: スタンダードプラン
                      updatedAt: '2022-06-07T14:59:43+09:00'
                      unReadCount: 0
      description: |
        指定したコメントIDを遡って既読する。しかし、スレッド内のメッセージに関しては、既読にしない。なので、スレッドを開いたときに、スレッドの最後のコメントIDに対して、APIを実行してください。
        RequestBodyは無し。
      tags:
        - channel_comment
  /channel_comments/reaction:
    parameters: []
    patch:
      summary: update channel comments reaction
      operationId: patch-channel_comments-id-reaction
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment:
                    $ref: '#/components/schemas/ThreadComment'
              examples:
                my-example:
                  value:
                    comment:
                      id: 1
                      content: test!!!
                      attachedFiles:
                        - id: 0
                          fileType: string
                          url: string
                          isDeleted: true
                          deletedAt: string
                          createdAt: string
                      profile:
                        id: 1
                        name: test_user
                        thumbnail: 'https://picsum.photos/id/237/200/300'
                        isProfilePublic: true
                      isRead: true
                      isDeleted: false
                      deletedAt: '2019-08-24T14:15:22Z'
                      createdAt: '2019-08-24T14:15:22Z'
                      updatedAt: '2019-08-24T14:15:22Z'
                      reactions:
                        - reaction:
                            id: 1
                            name: smail
                            image: "\U0001F974"
                          counts: 1
                          profiles:
                            - id: 10
                              name: testUser
                              thumbnail: 'https://picsum.photos/536/354'
                              isProfilePublic: true
                      threadInfo:
                        profiles:
                          - id: 2
                            name: test_user2
                            thumbnail: 'https://picsum.photos/seed/picsum/200/300'
                            isProfilePublic: true
                          - id: 3
                            name: test_user3
                            thumbnail: 'https://picsum.photos/id/1005/200/300'
                            isProfilePublic: true
                        commentCount: 2
                        lastCommentDateTime: '2019-08-24T14:15:22Z'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                reactionId:
                  type: integer
                commentId:
                  type: integer
      description: コメントにemojiリアクションする
      tags:
        - channel_comment
  /reactions:
    get:
      summary: get reactions
      tags:
        - reaction
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  reactionCategories:
                    type: array
                    items:
                      type: object
                      properties:
                        categoryName:
                          type: string
                        reactions:
                          type: array
                          items:
                            $ref: '#/components/schemas/Reaction'
              examples:
                my-example:
                  value:
                    reactionCategories:
                      - categoryName: People & Body
                        reactions:
                          - id: 102
                            name: original stamp
                            image: 'https://picsum.photos/200/300'
      operationId: get-reactions
      description: 絵文字もくは、自作絵文字一覧を取得する
    post:
      summary: create reaction
      operationId: post-reactions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  reaction:
                    $ref: '#/components/schemas/Reaction'
              examples:
                my-example:
                  value:
                    reaction:
                      id: 112
                      name: cry-face
                      image: 'https://picsum.photos/200/300'
      description: 自作絵文字を登録する
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                channelId:
                  type: integer
                name:
                  type: string
                image:
                  type: string
        description: ChannelIDを指定するのは、どのクラブが作ったのかを区別するため
      tags:
        - reaction
  /publish_pre_signed_url:
    post:
      summary: create pre-signed URL
      operationId: post-channel_comments-publish_pre_signed_url
      responses:
        '200':
          description: PreSignedUrlが、S3アップロード用のURLです。s3Urlが、コメント（ファイル）登録時のfilesのurlに埋め込むURLです。
          content:
            application/json:
              schema:
                type: object
                properties:
                  preSignedUrl:
                    type: string
                  s3Url:
                    type: string
              examples:
                my-example:
                  value:
                    preSignedUrl: 'https://shuriken-dev.s3.ap-northeast-1.amazonaws.com/attached-files/1/abc.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJTLX7NCWRPA2NHBA%2F20220708%2Fap-northeast-1%2Fs3%2Faws4_request&X-Amz-Date=20220708T140416Z&X-Amz-Expires=86400&X-Amz-SignedHeaders=host&x-id=PutObject&X-Amz-Signature=28d152cf695759fb6a6b86fe858c9ecafd8da298025b24481e2f69b7c153d198'
                    s3Url: 'https://shuriken-dev.s3.amazonaws.com/attached-files/1/abc.txt'
      tags:
        - channel_comment
      description: ファイルアップロード用のPresignedURLを発行する
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                fileName:
                  type: string
                contentType:
                  type: string
                  description: text/plain
        description: contentTypeは無くても良いといえば良いのですが、s3に登録する際のmetadataとして登録します。
    parameters: []
components:
  schemas:
    Club:
      title: Club
      x-stoplight:
        id: shvootrff5ayu
      type: object
      x-internal: false
      x-examples: {}
      properties:
        id:
          type: integer
        slug:
          type: string
        name:
          type: string
        clubColor:
          type: string
        icon:
          type: string
          nullable: true
        plans:
          type: array
          items:
            $ref: '#/components/schemas/Plan'
        unReadCount:
          type: integer
    Plan:
      title: Plan
      x-stoplight:
        id: ja941ygq9tcik
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        info:
          type: string
          nullable: true
        image:
          type: string
          nullable: true
    Channel:
      title: Channel
      x-stoplight:
        id: hlury3t0lkij6
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
        isOwner:
          type: boolean
        isJoinAsUser:
          type: boolean
        unReadCount:
          type: integer
        plans:
          type: array
          items:
            $ref: '#/components/schemas/Plan'
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
    ChannelComment:
      title: ChannelComment
      x-stoplight:
        id: fwiwjsd39d1o9
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
        attachedFiles:
          type: array
          items:
            $ref: '#/components/schemas/AttachedFile'
        profile:
          $ref: '#/components/schemas/Profile'
        isRead:
          type: boolean
        isDeleted:
          type: boolean
        deletedAt:
          type: string
          format: date-time
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        reactions:
          type: array
          items:
            $ref: '#/components/schemas/CommentReaction'
        threadInfo:
          type: object
          properties:
            profiles:
              type: array
              items:
                $ref: '#/components/schemas/Profile'
            commentCount:
              type: integer
            lastCommentDateTime:
              type: string
              format: date-time
    ThreadComment:
      title: ThreadComment
      x-stoplight:
        id: hj5aiy2641hlj
      type: object
      properties:
        id:
          type: integer
        content:
          type: string
        attachedFiles:
          type: array
          items:
            $ref: '#/components/schemas/AttachedFile'
        profile:
          $ref: '#/components/schemas/Profile'
        isRead:
          type: boolean
        isDeleted:
          type: boolean
        deletedAt:
          type: string
          format: date-time
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        reactions:
          type: array
          items:
            $ref: '#/components/schemas/CommentReaction'
    Profile:
      title: Profile
      x-stoplight:
        id: hwoemua95iq6t
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        thumbnail:
          type: string
          nullable: true
        isProfilePublic:
          type: boolean
    AttachedFile:
      title: AttachedFile
      x-stoplight:
        id: 3wu2bqofy2zmb
      type: object
      properties:
        id:
          type: integer
        fileType:
          type: string
        url:
          type: string
        isDeleted:
          type: boolean
        deletedAt:
          type: string
          nullable: true
        createdAt:
          type: string
    CommentReaction:
      title: CommentReaction
      x-stoplight:
        id: 1v12o75wh6474
      type: object
      properties:
        reaction:
          $ref: '#/components/schemas/Reaction'
        counts:
          type: integer
        profiles:
          type: array
          items:
            $ref: '#/components/schemas/Profile'
    Reaction:
      title: Reaction
      x-stoplight:
        id: 7i4icwmfs5380
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        image:
          type: string
          description: 'imageがhttp://では始まってる場合は、URL。始まってない場合は、文字コード'
      description: ''
